# List of games which can be submitted.

[owner]
name = "Neeraj Verma"

[[games]]
name = "Asphalt 9: Legends"
exec_name = "Asphalt9_w10_x86_rtl.exe"
website_url = "https://asphaltlegends.com/"
store_url = "https://www.microsoft.com/store/productId/9NZQPT0MWTD0"

[[games]]
name = "Forza Horizon 4"
exec_name = "ApplicationFrameHost.exe"
website_url = "https://forzamotorsport.net/en-us/games/fh4"
store_url = "https://www.microsoft.com/store/productId/9PNJXVCVWD4K"

[[games]]
name = "Battlefield™ V"
exec_name = "bfv.exe"
website_url = "https://www.ea.com/games/battlefield/battlefield-5"
store_url = "https://www.origin.com/ind/en-us/store/battlefield/battlefield-v"

[[games]]
name = "Burnout(TM) Paradise Remastered"
exec_name = "BurnoutPR.exe"
website_url = "https://www.ea.com/games/burnout/burnout-paradise-remastered"
store_url = "https://www.origin.com/ind/en-us/store/burnout/burnout-paradise-remastered"

[[games]]
name = "Battlefield 4"
exec_name = "bf4.exe"
website_url = "https://www.ea.com/games/battlefield/battlefield-4"
store_url = "https://www.origin.com/ind/en-us/store/battlefield/battlefield-4"

[[games]]
name = "Need For Speed Most Wanted"
exec_name = "NFS13.exe"
website_url = ""
store_url = ""

[[games]]
name = "Need for Speed The Run"
exec_name = "Need For Speed The Run.exe"
website_url = ""
store_url = ""

[[games]]
name = "Grand Theft Auto V"
exec_name = "GTA5.exe"
website_url = ""
store_url = ""

[[games]]
name = "Call of Duty Modern Warfare"
exec_name = "ModernWarfare.exe"
website_url = ""
store_url = ""